pipeline {
    agent any
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'maven:3.8.6'
                }
            }
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'maven:3.8.6'
                }
            }
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Build Image'){
            steps {
                script{
                    docker.withRegistry('us-central1-docker.pkg.dev/crp-dev-cloudsrv-test/jenkins-course/java', '') {
                        def customImage = docker.build("my-image:${env.BUILD_ID}")
                        /* Push the container to the custom Registry */
                        customImage.push()
                    }
                }
             }
       }
    }
}
